import {
  SiPython,
  SiMysql,
  SiGnubash,
  SiPhp,
  SiOpenjdk,
  SiCplusplus,
  SiRust,
  SiGo,
  SiKotlin,
  SiSwift,
  SiRuby,
  SiExpress,
  SiVuedotjs,
  SiSvelte,
  SiAngular,
  SiNuxt,
  SiRedux,
  SiDjango,
  SiFlask,
  SiLaravel,
  SiSpring,
  SiGithubactions,
  SiGitlab,
  SiDocker,
  SiKubernetes,
  SiCircleci,
  SiLinux,
  SiTerraform,
  SiNginx,
  SiJenkins,
  SiAnsible,
  SiPrometheus,
  SiGrafana,
  SiGooglecloud,
  SiCloudflare,
  SiVercel,
  SiNetlify,
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiBootstrap,
  SiVite,
  SiNodedotjs,
  SiMongodb,
  SiFirebase,
  SiGit,
  SiGithub,
  SiFigma,
  SiWordpress,
  SiYoutube,
} from "react-icons/si";
import {
  FaClapperboard,
  FaPaintbrush,
  FaPenNib,
  FaCloud,
} from "react-icons/fa6";

/* name → { Icon, color } — matched case-insensitively against skill names */
const TECH = {
  html: { Icon: SiHtml5, color: "#E44D26" },
  html5: { Icon: SiHtml5, color: "#E44D26" },
  css: { Icon: SiCss, color: "#1572B6" },
  css3: { Icon: SiCss, color: "#1572B6" },
  javascript: { Icon: SiJavascript, color: "#F7DF1E" },
  js: { Icon: SiJavascript, color: "#F7DF1E" },
  typescript: { Icon: SiTypescript, color: "#3178C6" },
  react: { Icon: SiReact, color: "#61DAFB" },
  "next.js": { Icon: SiNextdotjs, color: "#FFFFFF" },
  nextjs: { Icon: SiNextdotjs, color: "#FFFFFF" },
  tailwind: { Icon: SiTailwindcss, color: "#38BDF8" },
  tailwindcss: { Icon: SiTailwindcss, color: "#38BDF8" },
  bootstrap: { Icon: SiBootstrap, color: "#7952B3" },
  vite: { Icon: SiVite, color: "#A855F7" },
  node: { Icon: SiNodedotjs, color: "#5FA04E" },
  "node.js": { Icon: SiNodedotjs, color: "#5FA04E" },
  nodejs: { Icon: SiNodedotjs, color: "#5FA04E" },
  mongodb: { Icon: SiMongodb, color: "#47A248" },
  firebase: { Icon: SiFirebase, color: "#FFCA28" },
  git: { Icon: SiGit, color: "#F05032" },
  github: { Icon: SiGithub, color: "#FFFFFF" },
  figma: { Icon: SiFigma, color: "#F24E1E" },
  wordpress: { Icon: SiWordpress, color: "#21759B" },
  python: { Icon: SiPython, color: "#3776AB" },
  sql: { Icon: SiMysql, color: "#4479A1" },
  bash: { Icon: SiGnubash, color: "#4EAA25" },
  php: { Icon: SiPhp, color: "#777BB4" },
  java: { Icon: SiOpenjdk, color: "#E76F00" },
  openjdk: { Icon: SiOpenjdk, color: "#E76F00" },
  c: { Icon: SiCplusplus, color: "#00599C" },
  "c++": { Icon: SiCplusplus, color: "#00599C" },
  cpp: { Icon: SiCplusplus, color: "#00599C" },
  rust: { Icon: SiRust, color: "#F74C00" },
  go: { Icon: SiGo, color: "#00ADD8" },
  kotlin: { Icon: SiKotlin, color: "#7F52FF" },
  swift: { Icon: SiSwift, color: "#F05138" },
  ruby: { Icon: SiRuby, color: "#CC342D" },
  express: { Icon: SiExpress, color: "#FFFFFF" },
  vue: { Icon: SiVuedotjs, color: "#4FC08D" },
  svelte: { Icon: SiSvelte, color: "#FF3E00" },
  angular: { Icon: SiAngular, color: "#DD0031" },
  nuxt: { Icon: SiNuxt, color: "#00DC82" },
  redux: { Icon: SiRedux, color: "#764ABC" },
  django: { Icon: SiDjango, color: "#092E20" },
  flask: { Icon: SiFlask, color: "#FFFFFF" },
  laravel: { Icon: SiLaravel, color: "#FF2D20" },
  spring: { Icon: SiSpring, color: "#6DB33F" },
  "github actions": { Icon: SiGithubactions, color: "#2088FF" },
  githubactions: { Icon: SiGithubactions, color: "#2088FF" },
  gitlab: { Icon: SiGitlab, color: "#FC6D26" },
  docker: { Icon: SiDocker, color: "#2496ED" },
  kubernetes: { Icon: SiKubernetes, color: "#326CE5" },
  "ci/cd": { Icon: SiCircleci, color: "#F01F3D" },
  cicd: { Icon: SiCircleci, color: "#F01F3D" },
  linux: { Icon: SiLinux, color: "#FCC624" },
  terraform: { Icon: SiTerraform, color: "#7B42BC" },
  nginx: { Icon: SiNginx, color: "#009639" },
  jenkins: { Icon: SiJenkins, color: "#D24939" },
  ansible: { Icon: SiAnsible, color: "#EE0000" },
  prometheus: { Icon: SiPrometheus, color: "#E6522C" },
  grafana: { Icon: SiGrafana, color: "#F46800" },
  gcp: { Icon: SiGooglecloud, color: "#4285F4" },
  "google cloud": { Icon: SiGooglecloud, color: "#4285F4" },
  googlecloud: { Icon: SiGooglecloud, color: "#4285F4" },
  cloudflare: { Icon: SiCloudflare, color: "#F38020" },
  vercel: { Icon: SiVercel, color: "#FFFFFF" },
  netlify: { Icon: SiNetlify, color: "#00C7B7" },
  aws: { Icon: FaCloud, color: "#FF9900" },
  cloud: { Icon: FaCloud, color: "#FF9900" },
  "video editing": { Icon: FaClapperboard, color: "#9999FF" },
  premiere: { Icon: FaClapperboard, color: "#9999FF" },
  "premiere pro": { Icon: FaClapperboard, color: "#9999FF" },
  photoshop: { Icon: FaPaintbrush, color: "#31A8FF" },
  "content creation": { Icon: SiYoutube, color: "#FF0000" },
  youtube: { Icon: SiYoutube, color: "#FF0000" },
  writing: { Icon: FaPenNib, color: "#E2E8F0" },
};

/* Canonical logo keys offered by the admin skill picker */
export const TECH_LOGOS = [
  "html",
  "css",
  "javascript",
  "typescript",
  "python",
  "sql",
  "bash",
  "php",
  "openjdk",
  "c++",
  "rust",
  "go",
  "kotlin",
  "swift",
  "ruby",
  "react",
  "next.js",
  "tailwind",
  "bootstrap",
  "vite",
  "node",
  "express",
  "vue",
  "svelte",
  "angular",
  "nuxt",
  "redux",
  "django",
  "flask",
  "laravel",
  "spring",
  "mongodb",
  "firebase",
  "git",
  "github",
  "github actions",
  "gitlab",
  "docker",
  "kubernetes",
  "ci/cd",
  "linux",
  "terraform",
  "nginx",
  "jenkins",
  "ansible",
  "prometheus",
  "grafana",
  "aws",
  "gcp",
  "cloudflare",
  "vercel",
  "netlify",
  "figma",
  "wordpress",
  "premiere pro",
  "photoshop",
  "content creation",
  "youtube",
];

export default function TechIcon({
  name,
  className = "h-3.5 w-3.5",
  color: colorOverride,
}) {
  const key = String(name || "").toLowerCase().trim();
  const match = TECH[key];
  if (!match) return null;
  const { Icon, color } = match;
  return (
    <Icon
      className={className}
      style={{ color: colorOverride || color }}
      aria-hidden="true"
    />
  );
}
